In [2]:
import pandas as pd

In [3]:
data={"name":["Alice","Bob"],"Age":[25,30]}
df=pd.DataFrame(data)
df

    name  Age
0  Alice   25
1    Bob   30

In [4]:
lst=[["Alice",25],["Bob",30]]
df=pd.DataFrame(lst,columns=["Name","Age"])
df

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [8]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [9]:
df["name"]

KeyError: 'name'

In [ ]:
df[["name","Age"]]

    name  Age
0  Alice   25
1    Bob   30

In [ ]:
df.loc[0]

name    Alice
Age        25
Name: 0, dtype: object

In [ ]:
df.iloc[1]

name    Bob
Age      30
Name: 1, dtype: object

In [ ]:
df[df["Age"]>25]

  name  Age
1  Bob   30

In [ ]:
df["Gender"]=["F","M"]

In [ ]:
df.drop("Age",axis=1,inplace=True)

In [ ]:
df.isnull()

    name  Gender
0  False   False
1  False   False

In [ ]:
df.dropna()

    name Gender
0  Alice      F
1    Bob      M

In [ ]:
df.fillna(0)

    name Gender
0  Alice      F
1    Bob      M

In [ ]:
data1={"name":["Abhin","Aravind"],"Age":[20,19]}
df1=pd.DataFrame(data1)
data2={"name":["Mahima","Mahesh"],"Age":[20,50]}
df2=pd.DataFrame(data2)

In [ ]:
pd.merge(df1,df2,on="name")

Empty DataFrame
Columns: [name, Age_x, Age_y]
Index: []

In [ ]:
df1.join(df2, lsuffix="_left", rsuffix="_right")

  name_left  Age_left name_right  Age_right
0     Abhin        20     Mahima         20
1   Aravind        19     Mahesh         50

In [ ]:
df=pd.read_csv("titanic.csv")

In [ ]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [10]:
df.to_csv("output.csv",index=False)

In [12]:
print(df.sort_values('Age'))

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
print(df['Age'].apply(lambda x: x + 1))

0    26
1    31
Name: Age, dtype: int64

In [14]:
print(df['Name'].unique())

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [15]:
print(df['Age'].value_counts())

Age
25    1
30    1
Name: count, dtype: int64